---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed on Debian.
  apt: "name={{ apache_packages }} state={{ apache_packages_state }}"

- name: Ensure Apache packages are installed on Debian
  apt: "name={{ package }} state={{ state }}"
  with_items: "{{ apache_packages_extra }}"
  when: apache_packages_extra is defined and apache_packages_extra | length > 0
