---
- name: Add Apache2 repo.
  apt_repository: "repo=ppa:ondrej/apache2"

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed on Debian.
  apt: "name={{ apache_packages }} state={{ apache_packages_state }}"

- name: Ensure Apache packages are installed on Debian
  apt: "name={{ item.package }} state={{ item.state }}"
  loop: "{{ apache_packages_extra }}"
  when: apache_packages_extra is defined and apache_packages_extra | length > 0
